### ISSUE TITLE
Final Checklist

### ISSUE THREAD

**Issue by christoph-jaeger** [christoph-jaeger/github-portfolio#8]
### To-Do's

- [x] Cover letter done and exported as PDF → #6
- [x] CV done, exported as PDF and linked in Mini website → #5 
- [x] Mini website done and tested (Mobile works, no real Browser issues (Safari, Chrome, Firefox)) → #3 #4 
- [x] #7 merged
- [x] edit README
- [x] check, that it's available under https://github.christophjaeger.com/
- [x] [fill-out and send application](https://boards.greenhouse.io/github/jobs/2436236)
